{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sfdc-ka-generator.fullname" . }}
  labels:
    {{- include "sfdc-ka-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
  SF_SID: {{ .Values.secret.SF_SID | quote }}
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | quote }}
{{- end }}
