{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sfdc-ka-generator.serviceAccountName" . }}
  labels:
    {{- include "sfdc-ka-generator.labels" . | nindent 4 }}
{{- end }}
